# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-15 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('mbti1', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('mbti2', models.CharField(max_length=4)),
                ('match_score', models.BooleanField()),
            ],
            options={
                'db_table': 'match',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MbtiUser',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mbti1', models.CharField(max_length=4)),
                ('region', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'mbti_user',
                'managed': False,
            },
        ),
    ]
